package com.cosmeticPlatform.CosmeticPlatform.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;
import java.util.List;

@Entity
@Table(name = "product_bundle")
@Getter
@Setter
public class ProductBundle {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;

    private String description;

    private double discountPercentage; // e.g., 0.15 for 15% off

    private LocalDateTime validUntil;

    @ManyToMany
    @JoinTable(name = "bundle_products", joinColumns = @JoinColumn(name = "bundle_id"), inverseJoinColumns = @JoinColumn(name = "product_id"))
    private List<Product> products;

    // For "Frequently Bought Together" we might not persist it as a bundle entity,
    // but rather generate it dynamically. However, this entity can store curation
    // bundles.
    private boolean isSystemGenerated; // true if generated by algorithm
}
